version: '2'

services:
  sql:
    image: mysql:5.7
    ports:
      - 13306:3306
    environment:
      - "MYSQL_USER=matomo"
      - "MYSQL_DATABASE=matomo"
      - "MYSQL_PASSWORD=password"
      - "MYSQL_ROOT_PASSWORD=password"
    volumes:
      - ./.docker/postgres@9.6/sql/uuid-ossp.sql:/docker-entrypoint-initdb.d/00-uuid-ossp.sql:ro
      - ./.docker/postgres@9.6/custom-sql/:/docker-entrypoint-initdb.d/custom-sql/
      - database:/var/lib/mysql:cached
    restart: on-failure

  http:
    image: nginx:alpine
    volumes:
      - ./.docker/nginx@1.15/config/options.conf:/etc/nginx/conf.d/000-options.conf
      - ./.docker/nginx@1.15/config/vhost-prod.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html
    restart: on-failure
    ports:
      - 13080:80

  http-xdebug:
    image: nginx:alpine
    volumes:
      - ./.docker/nginx@1.15/config/options.conf:/etc/nginx/conf.d/000-options.conf
      - ./.docker/nginx@1.15/config/vhost-xdebug.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html
    restart: on-failure
    ports:
      - 13082:80

  fpm:
    build:
      context: .docker/php@7.2/fpm
    user: docker:docker
    volumes:
      - ./.docker/php@7.2/fpm/config/pool.ini:/usr/local/etc/php/pool.d/default.ini:ro
      - ./.docker/php@7.2/fpm/config/memory.ini:/usr/local/etc/php/conf.d/memory.ini:ro
      - ./:/var/www/html
    restart: on-failure

  fpm-xdebug:
    build:
      context: .docker/php@7.2/fpm-xdebug
    user: docker:docker
    volumes:
      - ./.docker/php@7.2/fpm/config/pool.ini:/usr/local/etc/php/pool.d/default.ini:ro
      - ./.docker/php@7.2/fpm/config/memory.ini:/usr/local/etc/php/conf.d/memory.ini:ro
      - ./.docker/php@7.2/cli-xdebug/config/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro
      - ./:/var/www/html
    restart: on-failure

  sh:
    build:
      context: .docker/php@7.2/cli
    user: docker:docker
    volumes:
      - ./.docker/php@7.2/cli/config/memory.ini:/usr/local/etc/php/conf.d/memory.ini:ro
      - ./:/var/www/html
    restart: "no"

  sh-xdebug:
    build:
      context: .docker/php@7.2/cli-xdebug
    user: docker:docker
    volumes:
      - ./.docker/php@7.2/cli-xdebug/config/memory.ini:/usr/local/etc/php/conf.d/memory.ini:ro
      - ./.docker/php@7.2/cli-xdebug/config/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro
      - ./:/var/www/html
    restart: "no"

  composer:
    extends:
      service: sh
    entrypoint: [ "composer" ]
    restart: "no"

  cli:
    extends:
      service: sh
    entrypoint: [ "console" ]
    restart: "no"

  cli-xdebug:
    extends:
      service: sh-xdebug
    entrypoint: [ "console" ]
    restart: "no"

  phpunit:
    extends:
      service: sh
    entrypoint: [ "bin/phpunit", "--configuration=phpunit.xml" ]
    restart: "no"

  phpunit-xdebug:
    extends:
      service: sh-xdebug
    entrypoint: [ "bin/phpunit", "--configuration=phpunit.xml" ]
    restart: "no"

volumes:
  database: {}